export const FETCH_BEGIN   = 'FETCH_BEGIN';
export const FETCH_SUCCESS_POPULAR = 'FETCH_SUCCESS_POPULAR';
export const FETCH_SUCCESS_TOP_RATED = 'FETCH_SUCCESS_TOP_RATED';
export const FETCH_SUCCESS_SEARCH = 'FETCH_SUCCESS_SEARCH';
export const FETCH_SUCCESS_DETAILS = 'FETCH_SUCCESS_DETAILS';
export const FETCH_FAILURE = 'FETCH_FAILURE';